### PR TITLE
Compatibility fixes/cleanup

### PR DESCRIPTION
**Pull request by habaneropep2019**
Remove unecessary files from old build system, temporary fixes for byacc 1.9 and ensure
G++ 8 compatibility.

### CODE REVIEW

**Comment by heliocastro** [comment]
Hello all..
Is too big, i need to look carefully and i will break down this pull request.
Some of the entries, like remove/add the header files doesn't make sense at all, so if you can properly breakdown this one, i'll appreciate.
Otherwise, i will be able to merge all things only on next Monday due the 'thing called life" :-D

**Comment by habaneropep2019** [comment]
Breakdown by commit:

**83c5a25**

- New changelog (changes-2.3.2-qtm1)
- Cleanup: Remove configs/*, as it is not needed for CMake. This accounts for a significant part of the commit.
- Not sure exactly why it shows that include/*.h headers are all removed and then re-added. On my local tree I had accidentally deleted them, and then reverted that change. It shouldn't have shown up in the commit as those changes hadn't even been committed locally yet, and I'm not sure how to remove that. Git is still fairly new to me so I may have done something without realizing it. I have not changed any of the header files in include/ in this commit.
- src/moc/CMakeLists.txt: Fixed bug on some systems where '/usr/bin/yacc' is a link to 'bison'. This ensures byacc is consistently used rather than bison.
- Cleanup: Remove src/moc/moc.t as it is no longer used with the build system.
- src/moc/moc.y: Temporary fix for newer versions of byacc. 'yydebug' breaks the build.

**50cb765**

- CMakeLists.txt: Remove MNG package
- changes-2.3.2-qtm2: New changelog
- doc/html/qimageio.html: Update documentation to indicate MNG is no longer supported.
- src/CMakeLists.txt: Remove MNG 
- src/kernel/CMakeLists.txt: Remove MNG
- src/kernel/qimage.cpp: Remove MNG from QImage class.

**8e3376a**

- doc/html/qimageio.html: Fix encoding issue in documentation introduced in 50cb765.

**Comment by habaneropep2019** [comment]
Hello,
Just curious if you've had a chance to review this pull request yet.

**Comment by EXL** [comment]
@heliocastro 

>src/moc/moc.y: Temporary fix for newer versions of byacc. 'yydebug' breaks the build.

Im also waiting for this fix too: #2
Because of this, it is impossible to build Qt 2 on modern Linux systems.

@binaryblob01 

>src/moc/CMakeLists.txt: Fixed bug on some systems where '/usr/bin/yacc' is a link to 'bison'. This ensures byacc is consistently used rather than bison.
>Cleanup: Remove src/moc/moc.t as it is no longer used with the build system.
>src/moc/moc.y: Temporary fix for newer versions of byacc. 'yydebug' breaks the build.

I think this changes can be divided into separate commit "about byacc". Same for GCC8 fixes. A large commit with the removal of a heap of files should be divided in a separate one too.

Use `git rebase -i` + squash and `git push -f` for it.

It would be great if this PR will be merged at least partially!

**Comment by habaneropep2019** [comment]
@heliocastro , I'd be happy to clean up the commits and re-submit a new PR if you'd like. Either way though, it would be great to get your input so that this PR can be moved forward for merge.

Thanks!

**Comment by habaneropep2019** [comment]
Just curious if you've gotten a chance to look over this. Let me know if I need to clean anything up.

**Comment by habaneropep2019** [comment]
Unfortunately, this PR has been open for a year. It's quite obvious this will never get merged. I will continue to maintain Qt2 but will have to diverge from this repository. Good luck!

**Pull request closed without merging**
